# PostgreSQL. Versions 9.4.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: utf8
  database: filmzeit_development
  username: postgres
  password: 5050
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: filmzeit_test
  username: postgres
  password: 5050
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: filmzeit_production
  username: postgres
  password: 5050
  host: localhost
